### ISSUE TITLE
Project yaml should have proper name

### ISSUE THREAD

**Issue by automatiek** [alifsemi/alif_M55-viewfinder#1]
According to CMSIS docs https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#project

Naming in `csolution.yaml` should change https://github.com/alifsemi/alif_M55-viewfinder/blob/d79821d168ffed5472a37dd897e28cda7c90f713/csolution.yaml#L37

As well as all the references throughout the project.

**Comment by AkiMakkonen-AlifSemi** [comment]
Thanks for pointing this out. Viewfinder demo inherits this behaviour from our template project https://github.com/alifsemi/alif_vscode-template
I agree this is sub optimal and it is fixed in our new template (currently in internal review). We will update the template and demo projects in the near future.
